### ISSUE TITLE
Update to work with jexl

### ISSUE THREAD

**Issue by cmdcolin** [cmdcolin/jb2export#12]
On branch jexl_updates and jbrowse-components branch export_svg_wiggle_jexl

I get this error

```
$ node dist/index.js --config data/config.json --defaultSession --out out.svg
Error: no plugin manager defined for renderer DivSequenceRenderer
    at new RendererType (/home/cdiesh/src/jb2export/node_modules/@jbrowse/core/pluggableElementTypes/renderers/RendererType.js:62:13)
    at DivSequenceRenderer.<anonymous> (/home/cdiesh/src/jb2export/node_modules/@jbrowse/core/pluggableElementTypes/renderers/ServerSideRendererType.js:48:291)
    at new ServerSideRenderer (/home/cdiesh/src/jb2export/node_modules/@jbrowse/core/pluggableElementTypes/renderers/ServerSideRendererType.js:59:19)
    at DivSequenceRenderer._createSuperInternal (/home/cdiesh/src/jb2export/node_modules/@jbrowse/plugin-sequence/dist/plugin-sequence.cjs.development.js:208:24)
    at new DivSequenceRenderer (/home/cdiesh/src/jb2export/node_modules/@jbrowse/plugin-sequence/dist/plugin-sequence.cjs.development.js:2122:19)
    at /home/cdiesh/src/jb2export/node_modules/@jbrowse/plugin-sequence/dist/plugin-sequence.cjs.development.js:2209:16
    at /home/cdiesh/src/jb2export/node_modules/@jbrowse/core/PluginManager.js:307:26
    at /home/cdiesh/src/jb2export/node_modules/@jbrowse/core/PluginManager.js:87:20
    at Array.forEach (<anonymous>)
    at /home/cdiesh/src/jb2export/node_modules/@jbrowse/core/PluginManager.js:86:26

```

**Comment by cmdcolin** [comment]
required getting latest sequence and variant plugins
